export const artistOptions =  [
        { value: 'Tranquilo', label: 'Tranquilo' },
        { value: 'Alan Uribe', label: 'Alan Uribe' },
        { value: 'Liliana Gálvez', label: 'Liliana Gálvez' },
        { value: 'Rubén Maya', label: 'Rubén Maya' },
        { value: 'Osiel Guerrero', label: 'Osiel Guerrero' },
        { value: 'Diego Afro', label: 'Diego Afro' },
        { value: 'Luis Selem', label: 'Luis Selem' },
        { value: 'Daniela Kum', label: 'Daniela Kum' },
        { value: 'Pyramid', label: 'Pyramid' },
        { value: 'Sara Celis', label: 'Sara Celis' },
        { value: 'Rafael Esquivel', label: 'Rafael Esquivel' },
        { value: 'Humberto Ramírez', label: 'Humberto Ramírez' },
        { value: 'Edgar Vázquez', label: 'Edgar Vázquez' },
        { value: 'El desaparecido Carbajal', label: 'El desaparecido Carbajal' },
        { value: 'Roa', label: 'Roa' },
        { value: 'Alberto Medina', label: 'Alberto Medina' },
        { value: 'Tania Quezada', label: 'Tania Quezada' },
        { value: 'Samantha Venegas', label: 'Samantha Venegas' },
        { value: 'Águila Herrea', label: 'Águila Herrea' },
        { value: 'Jorge Villanueva', label: 'Jorge Villanueva' },
        { value: 'T. Von Waberer GG', label: 'T. Von Waberer GG' },
        { value: 'Meme', label: 'Meme' },
        { value: 'Fernando Garrido', label: 'Fernando Garrido' },
        { value: 'Madriguera Gráfica', label: 'Madriguera Gráfica' },
        { value: 'Zuñiga', label: 'Zuñiga' },
        { value: 'Walter Cruz', label: 'Walter Cruz' },
        { value: 'Alan Altamirano', label: 'Alan Altamirano' },
        { value: 'Juan Muñoz', label: 'Juan Muñoz' },
        { value: 'Maestro Blanco', label: 'Maestro Blanco' },
        { value: 'Domingo Marin', label: 'Domingo Marin' },
        { value: 'Claudia Prudencia', label: 'Claudia Prudencia' },
        { value: 'Ángel Rejón', label: 'Ángel Rejón' },
        { value: 'Enrique Hernández', label: 'Enrique Hernández' },
        { value: 'Lucy Magaña', label: 'Lucy Magaña' },
        { value: 'Jaime Rincón', label: 'Jaime Rincón' },
        { value: 'Mauricio de la Vega', label: 'Mauricio de la Vega' },
        { value: 'SAMOT', label: 'SAMOT' },
        { value: 'Ericka Harsh', label: 'Ericka Harsh' },
        { value: 'Hugo Vázquez', label: 'Hugo Vázquez' },
        { value: 'Louis Doudier', label: 'Louis Doudier' },
        { value: 'Francisco Corzas', label: 'Francisco Corzas' },
        { value: 'Manuel Miguel', label: 'Manuel Miguel' },
        { value: 'Anguiano', label: 'Anguiano' },
        { value: 'Víctor López', label: 'Víctor López' },
        { value: 'Sandra López', label: 'Sandra López' },
        { value: 'Fabián de la Vega', label: 'Fabián de la Vega' },
        { value: 'Ticha González', label: 'Ticha González' },
        { value: 'Manuel Romero', label: 'Manuel Romero' },
        { value: 'Luis Filcer', label: 'Luis Filcer' },
        { value: 'Paulina Aguado', label: 'Paulina Aguado' },
        { value: 'Alejandra Bilbao', label: 'Alejandra Bilbao' },
        { value: 'Jonatan Olvera', label: 'Jonatan Olvera' },
        { value: 'Nonatzin Martínez', label: 'Nonatzin Martínez' },
        { value: 'Jorge Muñóz', label: 'Jorge Muñóz' },
        { value: 'Pablo Querea', label: 'Pablo Querea' },
        { value: 'Tzontli', label: 'Tzontli' },
        { value: 'Guadalupe Vélez', label: 'Guadalupe Vélez' },
        { value: 'Mari Mariel', label: 'Mari Mariel' },
        { value: 'Miguel Valiñas', label: 'Miguel Valiñas' },
        { value: 'Trinidad Osorio', label: 'Trinidad Osorio' },
        { value: 'Ramsés de la Cruz', label: 'Ramsés de la Cruz' },
        { value: 'Joaquín Ferreira', label: 'Joaquín Ferreira' },
        { value: 'Larsen', label: 'Larsen' },
        { value: 'Alix Yolitzin', label: 'Alix Yolitzin' },
        { value: 'Hugo Lugo', label: 'Hugo Lugo' },
        { value: 'Gustavo Pagís', label: 'Gustavo Pagís' },
        { value: 'Tempio Industriale', label: 'Tempio Industriale' },
        { value: 'Roberto Ugalde', label: 'Roberto Ugalde' },
        { value: 'Artífice Ácrata', label: 'Artífice Ácrata' },
        { value: 'Camila Villar', label: 'Camila Villar' },
        { value: 'Daniel Hernández', label: 'Daniel Hernández' },
        { value: 'Heczar Gómez', label: 'Heczar Gómez' },
        { value: 'Luis Doudier', label: 'Luis Doudier' },
    ]

    export const techniqueOptions =  [
        { value: 'Óleo sobre lienzo', label: 'Óleo sobre lienzo' },
        { value: 'Óleo sobre madera', label: 'Óleo sobre madera' },
        { value: 'Óleo sobre papel de algodón', label: 'Óleo sobre papel de algodón' },
        { value: 'Acrílico sobre lienzo', label: 'Acrílico sobre lienzo' },
        { value: 'Pastel sobre papel', label: 'Pastel sobre papel' },
        { value: 'Mixta', label: 'Mixta' },
        { value: 'Grabado sobre papel', label: 'Grabado sobre papel' },
        { value: 'Acuarela sobre papel', label: 'Acuarela sobre papel' },
        { value: 'Giclée', label: 'Giclée' },
        { value: 'Mixta sobre papel', label: 'Mixta sobre papel' },
        { value: 'Fotografía', label: 'Fotografía' },
        { value: 'Grafito sobre papel', label: 'Grafito sobre papel' },
        { value: 'Mixta sobre tela', label: 'Mixta sobre tela' },
        { value: 'Óleo sobre tela', label: 'Óleo sobre tela' },
        { value: 'Acero y Vidrio', label: 'Acero y Vidrio' },
        { value: 'Sanguina sobre papel', label: 'Sanguina sobre papel' },
        { value: 'Acuarela y tinta sobre papel Fabriano', label: 'Acuarela y tinta sobre papel Fabriano' },
        { value: 'Acero', label: 'Acero' },
        { value: 'Tinta china y gouache sobre papel', label: 'Tinta china y gouache sobre papel' },
        { value: 'Mixta sobre amate', label: 'Mixta sobre amate' },
        { value: 'Litografía', label: 'Litografía' },
        { value: 'Bronce', label: 'Bronce' },
        { value: 'Óleo sobre tela y madera', label: 'Óleo sobre tela y madera' },
        { value: 'Fibra de Vidrio intervenido', label: 'Fibra de Vidrio intervenido' },
        { value: 'Hueso Natural intervenido', label: 'Hueso Natural intervenido' },
        { value: 'Acrilico y carboncillo sobre tela', label: 'Acrilico y carboncillo sobre tela' },
        { value: 'Talavera y piel de cocodrilo sobre fibra de vidrio', label: 'Talavera y piel de cocodrilo sobre fibra de vidrio' },
        { value: 'Encausto sobre tela', label: 'Encausto sobre tela' },
        { value: 'óleo y óleo pastel sobre tela', label: 'óleo y óleo pastel sobre tela' },
        { value: 'Óleo y acrílico sobre lienzo', label: 'Óleo y acrílico sobre lienzo' },
        { value: 'Linograbado sobre papel', label: 'Linograbado sobre papel' },
        { value: 'Laca de poliuretano sobre MDF', label: 'Laca de poliuretano sobre MDF' },
        { value: 'Talavera y piel sobre fibra de vidrio', label: 'Talavera y piel sobre fibra de vidrio' },
        { value: 'Xilografía', label: 'Xilografía' },
        { value: 'Impronta de Grabado', label: 'Impronta de Grabado' },
        { value: 'Aerosol y marcador sobre cartón', label: 'Aerosol y marcador sobre cartón' },
        { value: 'Grafito y Carboncillo sobre papel de algodón', label: 'Grafito y Carboncillo sobre papel de algodón' },
        { value: 'Acrílico, pastel y carboncillo sobre tela', label: 'Acrílico, pastel y carboncillo sobre tela' },
        { value: 'Acrílico y pastel sobre tela', label: 'Acrílico y pastel sobre tela' },
        { value: 'Grabado en relieve sobre Panel ,acrilico y hoja de oro', label: 'Grabado en relieve sobre Panel ,acrilico y hoja de oro' },
        { value: 'Impronta de grabado en relieve sobre lienzo ,acrilico y hoja de oro', label: 'Impronta de grabado en relieve sobre lienzo ,acrilico y hoja de oro' },
        { value: 'Acrílico sobre madera', label: 'Acrílico sobre madera' },
        { value: 'Acrílico, carboncillo y lápiz sobre tela', label: 'Acrílico, carboncillo y lápiz sobre tela' },
        { value: 'Escultura de fibra de vidrio y resina', label: 'Escultura de fibra de vidrio y resina' },
    ]

    export const locationOptions =  [
        { value: 'Arte Berraco', label: 'Arte Berraco' },
        { value: 'Impulso Galería', label: 'Impulso Galería' },
        { value: 'Taller de artista', label: 'Taller de artista' },
        { value: 'ARS', label: 'ARS' },
        { value: 'Not So Fine Art Guadalajara', label: 'Not So Fine Art Guadalajara' },
        { value: 'Montana Shop Madrid', label: 'Montana Shop Madrid' },
        { value: 'Valle de Bravo', label: 'Valle de Bravo' },
        { value: 'Bodega del Pueblito', label: 'Bodega del Pueblito' },
        { value: 'AMARNA Miami', label: 'AMARNA Miami' },
    ]

    export const typeOptions =  [
        { value: 'Pintura', label: 'Pintura' },
        { value: 'Dibujo', label: 'Dibujo' },
        { value: 'Grabado', label: 'Grabado' },
        { value: 'Escultura', label: 'Escultura' },
        { value: 'Mixta', label: 'Mixta' },
        { value: 'Fotografía', label: 'Fotografía' },
        { value: 'Art Toy', label: 'Art Toy' },
        { value: 'Arte objeto', label: 'Arte objeto' },
    ]

    export const materialKeywordTags = [
    'Óleo', 'Acrílico', 'Técnica Mixta', 'Collage', 'Tela', 'Papel', 
    'Madera', 'Metal', 'Bronce', 'Grabado', 'Fotografía'
];